import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, Header, Footer, PageNumber, ShadingType, PageBreak, VerticalAlign, Numbering } from 'docx';
import type { StartupIdea, LegalDocumentData, LeanCanvas, SWOTAnalysis, PESTLEAnalysis, FinancialProjections, MarketingStrategy, ProjectRoadmap, PitchDeckSlide, BrandingGuide } from '../types';

// ... existing legal document generation functions ...

// Helper function for creating styled headings
const createHeading = (text: string, level: HeadingLevel = HeadingLevel.HEADING_2) => {
    return new Paragraph({
        text: text,
        heading: level,
        spacing: { before: 400, after: 200 },
        border: { bottom: { color: "auto", space: 1, value: "single", size: 4 } },
    });
};

const createSubHeading = (text: string) => new Paragraph({ text, heading: HeadingLevel.HEADING_3, spacing: { before: 300, after: 150 } });

// Helper for bullet points
const createBullet = (text: string) => new Paragraph({ text, bullet: { level: 0 } });

const generateLeanCanvasTable = (data: LeanCanvas): Table => {
    const cell = (title: string, content: string[] | string) => new TableCell({
        children: [
            new Paragraph({ children: [new TextRun({ text: title, bold: true })], spacing: { after: 100 } }),
            ...(Array.isArray(content) ? content.map(item => createBullet(item)) : [new Paragraph(content)])
        ],
        verticalAlign: VerticalAlign.TOP,
        borders: { top: { style: BorderStyle.SINGLE, size: 1 }, bottom: { style: BorderStyle.SINGLE, size: 1 }, left: { style: BorderStyle.SINGLE, size: 1 }, right: { style: BorderStyle.SINGLE, size: 1 } },
        padding: { top: 100, bottom: 100, left: 100, right: 100 },
    });

    return new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
            new TableRow({ children: [cell("Muammo", data.problem), cell("Yechim", data.solution), cell("Noyob Qiymat Taklifi", data.uniqueValueProposition), cell("Adolatsiz Ustunlik", data.unfairAdvantage), cell("Mijozlar Segmentlari", data.customerSegments)] }),
            new TableRow({ children: [cell("Asosiy Ko'rsatkichlar", data.keyMetrics), cell("Kanallar", data.channels), new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Xarajatlar Tuzilmasi", bold: true })], spacing: { after: 100 } }), ...data.costStructure.map(item => createBullet(item))], columnSpan: 1, verticalAlign: VerticalAlign.TOP }), new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Daromad Oqimlari", bold: true })], spacing: { after: 100 } }), ...data.revenueStreams.map(item => createBullet(item))], columnSpan: 2, verticalAlign: VerticalAlign.TOP }) ]}),
        ],
    });
};

const generateSwotTable = (data: SWOTAnalysis): Table => {
    const cell = (title: string, content: string[], color: string) => new TableCell({
        shading: { type: ShadingType.CLEAR, fill: color },
        children: [new Paragraph({ children: [new TextRun({ text: title, bold: true })], spacing: { after: 100 } }), ...content.map(item => createBullet(item))],
        verticalAlign: VerticalAlign.TOP,
    });
    return new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
            new TableRow({ children: [cell("Kuchli Tomonlar", data.strengths, "EAF1DF"), cell("Zaif Tomonlar", data.weaknesses, "F8D7DA")] }),
            new TableRow({ children: [cell("Imkoniyatlar", data.opportunities, "D1ECF1"), cell("Xavflar", data.threats, "FFF3CD")] }),
        ],
    });
};

export const generateFullBusinessPlanDocx = async (idea: StartupIdea): Promise<Blob> => {
    const doc = new Document({
        creator: "G'oya Mashinasi",
        title: `Biznes Reja: ${idea.projectName}`,
        styles: {
            paragraphStyles: [
                { id: "Normal", name: "Normal", run: { size: 24, font: "Times New Roman" }, paragraph: { spacing: { after: 120 } } },
                { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", run: { size: 48, bold: true, color: "1E40AF" }, paragraph: { alignment: AlignmentType.CENTER, spacing: { after: 240 } } },
                { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", run: { size: 28, bold: true, color: "1D4ED8" }, paragraph: { spacing: { before: 240, after: 120 } } },
                { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", run: { size: 24, bold: true, color: "3B82F6" }, paragraph: { spacing: { before: 200, after: 100 } } },
            ]
        },
        sections: [{
            headers: { default: new Header({ children: [new Paragraph({ border: { bottom: { color: "auto", space: 1, value: "single", size: 6 } }, children: [new TextRun({ text: idea.projectName, bold: true }), new TextRun({ text: "\tGenerated by G'oya Mashinasi", color: "999999" })] })] }) },
            footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun("Sahifa "), new TextRun({ children: [PageNumber.CURRENT] }), new TextRun(" / "), new TextRun({ children: [PageNumber.TOTAL_PAGES] })] })] }) },
            children: [
                new Paragraph({ text: idea.projectName, heading: HeadingLevel.HEADING_1, spacing: { after: 400 } }),
                new Paragraph({ text: "Biznes Reja To'plami", alignment: AlignmentType.CENTER, run: { size: 28, italics: true }, spacing: { after: 800 } }),
                new Paragraph({ text: idea.description, alignment: AlignmentType.CENTER, run: { size: 24 }, indent: { left: 720, right: 720 }, spacing: { after: 800 } }),
                new Paragraph({ text: `Generatsiya qilingan sana: ${new Date().toLocaleDateString('uz-UZ')}`, alignment: AlignmentType.CENTER, run: { color: "595959" } }),
                new Paragraph({ children: [new PageBreak()] }),

                createHeading("Lean Canvas"), generateLeanCanvasTable(idea.leanCanvas),
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("SWOT Tahlili"), generateSwotTable(idea.swotAnalysis),
                
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("PESTLE Tahlili"),
                ...Object.entries(idea.pestleAnalysis).flatMap(([key, value]) => [createSubHeading(key.charAt(0).toUpperCase() + key.slice(1)), ...value.map(item => createBullet(item))]),

                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Maqsadli Auditoriya Personajlari"),
                new Paragraph(idea.targetAudiencePersonas.summary),
                ...idea.targetAudiencePersonas.personas.flatMap(p => [
                    createSubHeading(p.name),
                    new Paragraph(`Demografiya: ${p.demographics}`),
                    new Paragraph(`Hikoya: ${p.story}`),
                    new Paragraph({ text: "Maqsadlari:", run: { bold: true } }), ...p.goals.map(item => createBullet(item)),
                    new Paragraph({ text: "Og'riqli nuqtalari:", run: { bold: true } }), ...p.painPoints.map(item => createBullet(item)),
                ]),

                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Raqobatchilar Tahlili"),
                new Paragraph(idea.competitiveAnalysis.marketPositioningStatement),
                ...idea.competitiveAnalysis.competitors.flatMap(c => [
                    createSubHeading(c.name),
                    new Paragraph({ text: "Kuchli tomonlari:", run: { bold: true } }), ...c.strengths.map(item => createBullet(item)),
                    new Paragraph({ text: "Zaif tomonlari:", run: { bold: true } }), ...c.weaknesses.map(item => createBullet(item)),
                    new Paragraph({ text: "Yengish strategiyasi:", run: { bold: true } }), new Paragraph(c.strategyToBeat),
                ]),

                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Marketing Strategiyasi"),
                createSubHeading("Maqsadli Auditoriya"), new Paragraph(idea.marketingStrategy.targetAudience),
                createSubHeading("Kanallar"), ...idea.marketingStrategy.channels.map(item => createBullet(item)),
                createSubHeading("Asosiy Xabar (Key Message)"), new Paragraph(idea.marketingStrategy.keyMessage),
                
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Monetizatsiya Strategiyasi"),
                createSubHeading(idea.monetizationStrategy.primaryModel),
                new Paragraph(idea.monetizationStrategy.description),
                new Paragraph({ text: "Asoslash:", run: { bold: true } }), new Paragraph(idea.monetizationStrategy.justification),
                new Table({
                    width: { size: 100, type: WidthType.PERCENTAGE },
                    rows: [
                        new TableRow({ children: idea.monetizationStrategy.pricingTiers.map(tier => new TableCell({ children: [new Paragraph({ text: tier.name, run: { bold: true } })] })) }),
                        new TableRow({ children: idea.monetizationStrategy.pricingTiers.map(tier => new TableCell({ children: [new Paragraph({ text: tier.price, run: { bold: true } })] })) }),
                        new TableRow({ children: idea.monetizationStrategy.pricingTiers.map(tier => new TableCell({ children: tier.features.map(f => createBullet(f)) })) }),
                    ]
                }),
                
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Jamoa Tuzilmasi"),
                new Paragraph(`Ishga olish ustuvorligi: ${idea.teamStructure.hiringPriorities}`),
                ...idea.teamStructure.roles.flatMap(r => [
                    createSubHeading(r.role),
                    new Paragraph({ text: "Mas'uliyatlar:", run: { bold: true } }), ...r.responsibilities.map(item => createBullet(item)),
                    new Paragraph({ text: "Kerakli ko'nikmalar:", run: { bold: true } }), ...r.requiredSkills.map(item => createBullet(item)),
                ]),
                
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Moliyaviy Prognozlar"),
                createSubHeading("Daromadlar Prognozi"),
                new Table({
                    width: { size: 100, type: WidthType.PERCENTAGE },
                    rows: [
                        new TableRow({ children: [new TableCell({ children: [new Paragraph("Yil")] }), new TableCell({ children: [new Paragraph("Prognoz qilingan daromad")] })] }),
                        ...idea.financialProjections.revenueForecast.map(p => new TableRow({ children: [new TableCell({ children: [new Paragraph(`${p.year}-yil`)] }), new TableCell({ children: [new Paragraph(new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(p.revenue))] })] }))
                    ],
                }),
                createSubHeading("Zararsizlik Nuqtasi Tahlili"), new Paragraph(idea.financialProjections.breakEvenAnalysis),
                createSubHeading("Asosiy Taxminlar"), ...idea.financialProjections.keyAssumptions.map(item => createBullet(item)),

                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Risklar Tahlili"),
                new Paragraph(idea.riskAnalysis.summary),
                new Table({
                    width: { size: 100, type: WidthType.PERCENTAGE },
                    rows: [
                        new TableRow({ children: ["Risk", "Ehtimollik", "Ta'sir", "Kamaytirish strategiyasi"].map(text => new TableCell({ children: [new Paragraph({ text, run: { bold: true } })]}))}),
                        ...idea.riskAnalysis.risks.map(risk => new TableRow({
                            children: [
                                new TableCell({ children: [new Paragraph(risk.description)] }),
                                new TableCell({ children: [new Paragraph(risk.likelihood)] }),
                                new TableCell({ children: [new Paragraph(risk.impact)] }),
                                new TableCell({ children: [new Paragraph(risk.mitigation)] }),
                            ]
                        }))
                    ]
                }),
                
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Loyiha Yo'l Xaritasi"),
                ...idea.projectRoadmap.phases.flatMap(phase => [createSubHeading(phase.name), ...phase.tasks.map(task => createBullet(`${task.name} (${task.durationDays} kun, ${task.startDate} dan boshlab)`))]),
                
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Pitch Deck Slaydlari"),
                ...idea.pitchDeck.flatMap(slide => [createSubHeading(slide.title), ...slide.content.map(item => createBullet(item))]),
                
                new Paragraph({ children: [new PageBreak()] }),
                createHeading("Brending"),
                createSubHeading("Ranglar Palitrasi"),
                ...idea.brandingGuide.colorPalette.map(color => new Paragraph({ children: [new TextRun({ text: `■ ${color.name}: `, style: "Normal" }), new TextRun({ text: color.hex, style: "Normal" })] })),
                createSubHeading("Tipografiya"), new Paragraph(`${idea.brandingGuide.typography.fontFamily} - ${idea.brandingGuide.typography.usage}`),
            ]
        }],
    });
    return Packer.toBlob(doc);
};

export const generateCharter = async (data: LegalDocumentData): Promise<Blob> => {
    const doc = new Document({
        creator: "G'oya Mashinasi",
        title: `${data.companyName} Ustavi`,
        description: "MChJ Ustavi",
        styles: {
            paragraphStyles: [
                { id: "Normal", name: "Normal", run: { size: 24, font: "Times New Roman" }, paragraph: { spacing: { after: 120 } } },
                { id: "heading1", name: "Heading 1", basedOn: "Normal", run: { size: 28, bold: true }, paragraph: { alignment: AlignmentType.CENTER, spacing: { before: 240, after: 120 } } },
            ],
        }
    });

    doc.addSection({
        children: [
            new Paragraph({ text: `«TASDIQLAYMAN»`, alignment: AlignmentType.END }),
            new Paragraph({ text: `«${data.companyName}» MChJ`, alignment: AlignmentType.END }),
            new Paragraph({ text: `yagona ta'sischisi ${data.founderName}`, alignment: AlignmentType.END }),
            new Paragraph({ text: `_______________________`, alignment: AlignmentType.END, spacing: { after: 400 } }),
            new Paragraph({ text: `${data.companyName} Mas'uliyati Cheklangan Jamiyati USTAVI`, style: "heading1", spacing: { after: 400 } }),
            
            new Paragraph({ text: "1. UMUMIY QOIDALAR", style: "heading1" }),
            new Paragraph({ text: `1.1. Ushbu Ustav «${data.companyName}» mas’uliyati cheklangan jamiyatining (keyingi o‘rinlarda «Jamiyat» deb yuritiladi) ta’sis hujjati hisoblanadi.`, style: "Normal" }),
            new Paragraph({ text: `1.2. Jamiyat O‘zbekiston Respublikasining amaldagi qonunchiligiga muvofiq tashkil etilgan bo‘lib, o‘z faoliyatini O‘zbekiston Respublikasi Konstitutsiyasi, Fuqarolik kodeksi, «Mas’uliyati cheklangan hamda qo‘shimcha mas’uliyatli jamiyatlar to‘g‘risida»gi Qonuni va boshqa qonun hujjatlari hamda ushbu Ustav asosida amalga oshiradi.`, style: "Normal" }),
            new Paragraph({ text: `1.3. Jamiyatning nomi: ${data.companyName}`, style: "Normal" }),
            
            new Paragraph({ text: "2. JAMiyatNING TA'SISCILARI", style: "heading1" }),
            new Paragraph({ text: `2.1. Jamiyatning yagona ta'sischisi: ${data.founderName}, pasport ${data.passportSerial} ${data.passportNumber}, yashash manzili: ${data.address}.`, style: "Normal" }),

            new Paragraph({ text: "...", style: "Normal" }),
            new Paragraph({ text: "[...Ustavning qolgan standart bandlari...]", alignment: AlignmentType.CENTER, run: { color: '888888' } }),
            new Paragraph({ text: "...", style: "Normal" }),
            
            new Paragraph({ text: "10. YAKUNIY QOIDALAR", style: "heading1" }),
            new Paragraph({ text: `10.1. Ushbu Ustav Jamiyat davlat ro‘yxatidan o‘tkazilgan paytdan e’tiboran kuchga kiradi.`, style: "Normal" }),
            new Paragraph({ text: `TA'SISCHI:`, spacing: { before: 600 } }),
            new Paragraph({ text: `_______________________ ${data.founderName}`, spacing: { before: 400 } }),
        ],
    });

    return Packer.toBlob(doc);
};

const createNumberedAbstract = (numbering: Numbering) => {
    return numbering.createAbstractNumbering([
        {
            level: 0,
            format: "decimal",
            text: "%1.",
            alignment: AlignmentType.START,
            style: {
                paragraph: {
                    indent: { left: 720, hanging: 360 },
                },
            },
        },
        {
            level: 1,
            format: "decimal",
            text: "%1.%2.",
            alignment: AlignmentType.START,
            style: {
                paragraph: {
                    indent: { left: 1440, hanging: 360 },
                },
            },
        }
    ]);
};

export const generateProtocol = async (data: LegalDocumentData): Promise<Blob> => {
     const doc = new Document({
        creator: "G'oya Mashinasi",
        styles: { paragraphStyles: [{ id: "Normal", name: "Normal", run: { size: 24, font: "Times New Roman" }, paragraph: { spacing: { after: 120 } } }, { id: "heading1", name: "Heading 1", basedOn: "Normal", run: { size: 28, bold: true }, paragraph: { alignment: AlignmentType.CENTER, spacing: { before: 240, after: 120 } } }] }
    });
    
    const numbering = new Numbering({});
    const abstract = createNumberedAbstract(numbering);
    const concrete = numbering.createConcreteNumbering(abstract);

    doc.addSection({
        children: [
            new Paragraph({ text: `«${data.companyName}» MChJ yagona ta'sischisining 1-sonli YIG'ILISH BAYONNOMASI`, style: "heading1" }),
            new Paragraph({ children: [new TextRun({ text: "Toshkent sh." }), new TextRun({ text: `\t\t\t\t${new Date().toLocaleDateString('uz-UZ')}` })]}),
            new Paragraph({ text: `Yagona ta'sischi: ${data.founderName}, pasport ${data.passportSerial} ${data.passportNumber}, yashash manzili: ${data.address}.`, spacing: { after: 240 } }),

            new Paragraph({ text: "KUN TARTIBI:", run: { bold: true }, spacing: { before: 240, after: 240 } }),
            new Paragraph({ text: `1. "${data.companyName}" Mas’uliyati cheklangan jamiyatini tashkil etish to‘g‘risida.`, numbering: { reference: concrete, level: 0 } }),
            new Paragraph({ text: `2. Jamiyat Ustavini tasdiqlash to‘g‘risida.`, numbering: { reference: concrete, level: 0 } }),
            new Paragraph({ text: `3. Jamiyat direktorini tayinlash to‘g‘risida.`, numbering: { reference: concrete, level: 0 } }),

            new Paragraph({ text: `Kun tartibidagi masalalar bo'yicha TINGLANDI:`, run: { bold: true }, spacing: { before: 240 } }),
            new Paragraph({ text: `Yagona ta’sischi ${data.founderName} so‘zga chiqib, O‘zbekiston Respublikasi hududida tadbirkorlik faoliyatini amalga oshirish maqsadida «${data.companyName}» MChJni tashkil etishni taklif qildi.`, spacing: { after: 240 } }),

            new Paragraph({ text: "QAROR QILINDI:", run: { bold: true }, spacing: { before: 240 } }),
            new Paragraph({ text: `1. "${data.companyName}" Mas’uliyati cheklangan jamiyati tashkil etilsin.`, numbering: { reference: concrete, level: 0 } }),
            new Paragraph({ text: `2. Jamiyatning Ustavi ilova qilingan tahrirda tasdiqlansin.`, numbering: { reference: concrete, level: 0 } }),
            new Paragraph({ text: `3. ${data.directorName} Jamiyat direktori lavozimiga tayinlansin.`, numbering: { reference: concrete, level: 0 } }),

            new Paragraph({ text: `Yagona ta'sischi:`, spacing: { before: 600 } }),
            new Paragraph({ text: `_______________________ ${data.founderName}`, spacing: { before: 400 } }),
        ]
    });
    return Packer.toBlob(doc);
};

export const generateOrder = async (data: LegalDocumentData): Promise<Blob> => {
    const doc = new Document({
        creator: "G'oya Mashinasi",
        styles: { paragraphStyles: [{ id: "Normal", name: "Normal", run: { size: 24, font: "Times New Roman" }, paragraph: { spacing: { after: 120 } } }, { id: "heading1", name: "Heading 1", basedOn: "Normal", run: { size: 28, bold: true }, paragraph: { alignment: AlignmentType.CENTER, spacing: { before: 240, after: 120 } } }] }
    });

    doc.addSection({
        children: [
            new Paragraph({ text: `«${data.companyName}» MChJ`, alignment: AlignmentType.START, run: { bold: true } }),
            new Paragraph({ text: "1-sonli BUYRUQ", style: "heading1" }),
            new Paragraph({ children: [new TextRun({ text: "Toshkent sh." }), new TextRun({ text: `\t\t\t\t${new Date().toLocaleDateString('uz-UZ')}` })]}),
            
            new Paragraph({ text: `Direktorni ishga qabul qilish to'g'risida`, run: { bold: true }, spacing: { before: 240, after: 240 } }),
            
            new Paragraph({ text: `«${data.companyName}» MChJ yagona ta'sischisining 1-sonli Yig'ilish bayonnomasiga asosan,` }),
            
            new Paragraph({ text: "BUYURAMAN:", run: { bold: true }, alignment: AlignmentType.CENTER, spacing: { before: 240, after: 240 } }),

            new Paragraph({ text: `1. ${data.directorName} ${new Date().toLocaleDateString('uz-UZ')} sanadan e'tiboran «${data.companyName}» MChJ direktori lavozimiga ishga qabul qilinsin.` }),
            new Paragraph({ text: `2. O'z xizmat vazifalarini bajarishga kirishsin.` }),
            
            new Paragraph({ text: `Asos: Ta'sischining 1-sonli Yig'ilish bayonnomasi.`, spacing: { before: 240 } }),
            
            new Paragraph({ text: `Yagona ta'sischi:`, spacing: { before: 600 } }),
            new Paragraph({ text: `_______________________ ${data.founderName}`, spacing: { before: 400 } }),
        ]
    });
    return Packer.toBlob(doc);
};